services:
    nginx:
        image: nginx:latest
        volumes:
           - ./:/var/www
           - ./_docker/nginx/conf.d:/etc/nginx/conf.d
        ports:
            - "8876:80"
        depends_on:
           - app
        container_name: task_nginx

    app:
        volumes:
            - ./:/var/www
        build:
            context: .
            dockerfile: _docker/app/Dockerfile
        container_name: task_app
        depends_on:
            - db
    db:
        image: mysql:8.0
        restart: always
        volumes:
            - ./tmp/db:/var/lib/mysql
        environment:
            MYSQL_DATABASE: task_db
            MYSQL_ROOT_PASSWORD: root
        ports:
            - "3806:3306"
        command: mysqld --character-set-server=utf8 --collation-server=utf8_unicode_ci
        container_name: task_mysql
    node:
         build:
             context: .
             dockerfile: _docker/nodejs/Dockerfile
         tty: true
         ports:
             - "5173:5173"
         working_dir: /var/www
         volumes:
             - .:/var/www
